// src/commands/release.ts

import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import apiClient from "../lib/api-client";
import Table from "cli-table3";
import fs from "fs";
import FormData from "form-data";
import { handleApiError } from "../lib/error-handler";
import { resolveAppId } from "../lib/app-resolver";
import { createBundleAndZip } from "../lib/bundler";

export function registerReleaseCommands(program: Command) {
  const releaseCommand = program
    .command("release")
    .description("Gestiona los despliegues de actualizaciones");

  releaseCommand
    .command("publish <appName>")
    .description("Publica una nueva actualización desde un archivo .zip")
    .argument(
      "[zipPath]",
      "Ruta al .zip. Si se omite, se intentará crear automáticamente.",
    )
    .option("-c, --channel <channel>", "Canal de despliegue", "Staging")
    .option(
      "-t, --target-version <version>",
      "Versión binaria objetivo (ej. 1.0.0)",
      "1.0.0",
    )
    .option(
      "-m, --mandatory",
      "Marcar la actualización como obligatoria",
      false,
    )
    .option(
      "-r, --rollout <percentage>",
      "Porcentaje de despliegue (1-100)",
      "100",
    )
    .action(async (appName, zipPath, options) => {
      const appId = await resolveAppId(appName);
      if (!appId) {
        return;
      }
      let finalZipPath = zipPath;

      if (!finalZipPath) {
        const autoGeneratedPath = createBundleAndZip();
        if (!autoGeneratedPath) {
          console.log(
            chalk.red(
              "No se pudo generar el bundle. Por favor, proporciona la ruta a un archivo .zip manualmente.",
            ),
          );
          return;
        }
        finalZipPath = autoGeneratedPath;
      }

      if (!fs.existsSync(finalZipPath)) {
        console.log(
          chalk.red(`Error: El archivo '${finalZipPath}' no existe.`),
        );
        return;
      }

      const form = new FormData();
      form.append("bundle", fs.createReadStream(finalZipPath));
      form.append("appId", appId);
      form.append("channel", options.channel);
      form.append("targetBinaryVersion", options.targetVersion);
      form.append("isMandatory", options.mandatory.toString());
      form.append("rolloutPercentage", options.rollout);

      const spinner = ora(
        `Subiendo y publicando actualización para la app '${appId}'...`,
      ).start();
      try {
        await apiClient.post("/publish", form, {
          headers: form.getHeaders(),
        });
        spinner.succeed(chalk.green("¡Actualización publicada con éxito!"));
      } catch (error) {
        spinner.fail("Fallo al publicar la actualización.");
        handleApiError(error);
      } finally {
        if (!zipPath && fs.existsSync(finalZipPath)) {
          fs.unlinkSync(finalZipPath);
        }
      }
    });

  releaseCommand
    .command("metrics <releaseId>")
    .description(
      "Muestra las métricas de instalación para una release específica",
    )
    .action(async (releaseId: string) => {
      const spinner = ora(
        `Obteniendo métricas para la release '${releaseId}'...`,
      ).start();
      try {
        const response = await apiClient.get(`/releases/${releaseId}/metrics`);
        const metrics = response.data;

        if (!metrics) {
          spinner.fail(
            "No se recibió una respuesta de métricas válida del servidor.",
          );
          return;
        }

        spinner.succeed(
          chalk.green(
            `Métricas de Despliegue para la release ${chalk.bold(releaseId)}:`,
          ),
        );

        // Calculamos la tasa de éxito para mostrar un porcentaje útil
        const successRate =
          metrics.total > 0 ? (metrics.success / metrics.total) * 100 : 0;

        console.log(""); // Línea en blanco para espaciar
        console.log(
          `  Instalaciones Exitosas:  ${chalk.green.bold("✅ " + metrics.success)}`,
        );
        console.log(
          `  Instalaciones Fallidas:  ${chalk.red.bold("❌ " + metrics.failure)}`,
        );
        console.log("  -----------------------------------");
        console.log(`  Total de Reportes:       ${chalk.bold(metrics.total)}`);
        console.log(
          `  Tasa de Éxito:           ${chalk.blue.bold(successRate.toFixed(2) + "%")}`,
        );
        console.log("");
      } catch (error) {
        spinner.fail("No se pudieron obtener las métricas.");
        handleApiError(error);
      }
    });

  releaseCommand
    .command("list <appName>")
    .alias("ls")
    .description("Muestra el historial de releases para una aplicación")
    .action(async (appName: string) => {
      const appId = await resolveAppId(appName);
      if (!appId) {
        return;
      }
      const spinner = ora(
        `Obteniendo historial para la app '${appId}'...`,
      ).start();
      try {
        const response = await apiClient.get(`/apps/${appId}/releases`);
        spinner.succeed("Historial de releases:");

        const table = new Table({
          head: [
            chalk.cyan("ID"),
            chalk.cyan("Canal"),
            chalk.cyan("Versión Target"),
            chalk.cyan("Obligatoria"),
            chalk.cyan("Activa"),
          ],
        });

        response.data.forEach((release: any) => {
          table.push([
            release.id,
            release.channel,
            release.targetBinaryVersion,
            release.isMandatory ? "Sí" : "No",
            release.isActive ? "✅" : "❌",
          ]);
        });

        console.log(table.toString());
      } catch (error) {
        spinner.fail("No se pudo obtener el historial.");
        handleApiError(error);
      }
    });

  releaseCommand
    .command("rollback <appName>")
    .description("Desactiva la última release de un canal específico")
    .option(
      "-c, --channel <channel>",
      "Canal del que se hará el rollback",
      "Production",
    )
    .action(async (appName, options) => {
      const appId = await resolveAppId(appName);
      if (!appId) return;

      const spinner = ora(
        `Buscando la última release activa para '${appName}' en el canal '${options.channel}'...`,
      ).start();
      try {
        const response = await apiClient.get(`/apps/${appId}/releases`);
        const releases = response.data as any[];
        const latestActiveRelease = releases.find(
          (r) => r.channel === options.channel && r.isActive,
        );

        if (!latestActiveRelease) {
          spinner.warn(
            chalk.yellow(
              `No se encontró ninguna release activa en el canal '${options.channel}' para hacer rollback.`,
            ),
          );
          return;
        }

        spinner.text = `Realizando rollback para la release ID: ${latestActiveRelease.id}...`;

        await apiClient.post(`/releases/${latestActiveRelease.id}/rollback`);

        spinner.succeed(
          chalk.green(`Rollback exitoso. La release ya no está activa.`),
        );
      } catch (error) {
        spinner.fail("No se pudo realizar el rollback.");
        handleApiError(error);
      }
    });

  releaseCommand
    .command("promote <appName>")
    .description("Promueve la última release de un canal a otro")
    .option("-f, --from <channel>", "Canal de origen", "Staging")
    .option("-t, --to <channel>", "Canal de destino", "Production")
    .action(async (appName, options) => {
      const appId = await resolveAppId(appName);
      if (!appId) return;

      const spinner = ora(
        `Buscando la última release en '${options.from}' para promover a '${options.to}'...`,
      ).start();
      try {
        // 1. Obtenemos el historial para encontrar la última release del canal de origen
        const response = await apiClient.get(`/apps/${appId}/releases`);
        const releases = response.data as any[];
        const latestReleaseToPromote = releases.find(
          (r) => r.channel === options.from,
        );

        if (!latestReleaseToPromote) {
          spinner.warn(
            chalk.yellow(
              `No se encontró ninguna release en el canal '${options.from}' para promover.`,
            ),
          );
          return;
        }

        spinner.text = `Promoviendo la release ID: ${latestReleaseToPromote.id}...`;

        // 2. Llamamos al endpoint de promote
        await apiClient.post(`/releases/${latestReleaseToPromote.id}/promote`, {
          toChannel: options.to,
        });

        spinner.succeed(
          chalk.green(
            `¡Release promovida con éxito de '${options.from}' a '${options.to}'!`,
          ),
        );
      } catch (error) {
        spinner.fail("No se pudo promover la release.");
        handleApiError(error);
      }
    });
}
